### ISSUE TITLE
No error thrown when signed with incorrect private key

### ISSUE THREAD

**Issue by TheReturnOfJan** [jjyr/ckb-dynamic-loading-secp256k1#2]
When using a private key that does not correspond to the pubkey hash in the args, the script verification still succeeds. See here:
https://github.com/TheReturnOfJan/ckb-dynamic-loading-secp256k1/blob/18af9f5ac583631bec70c620fe6e9ab402cab8e2/tests/src/tests.rs#L212
(the unwrap_err fails)

**Comment by jjyr** [comment]
Thanks for reporting the issue.

I misunderstand the interface in the C library.

https://github.com/jjyr/ckb-dynamic-loading-secp256k1/commit/d15c450f1e0df60b65820e9b8d7d5d4b61010427
